language: node_js
sudo: false
os:
  - linux
  - osx
node_js:
  - 12
  - 11
  - 10
  - 9
  - 8
  - 7
before_install: dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@^5.8
install:
  - npm ci
script:
  - npm test
